# Site
name: "Qraft Technologies Blog"
title: "Qraft Tech Blog"
description: "크래프트테크놀로지스의 기술과 성과, 사내 이야기를 공유합니다."
logo: 'assets/images/favicon.jpg'
favicon: 'assets/images/favicon.jpg'
url: "https://qraftech.github.io"
baseurl: ""
# google_analytics: 'UA-145461596-1'
# disqus: 'demowebsite'
# mailchimp-list:
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Qraft:
    name: Qraft
    display_name: Qraft
    avatar: 'assets/images/team/logo.jpg'
    email: qraftec@qraftec.com
    description: "The Artificial Intelligence in Finance Sector"
  김형식:
    name: 김형식
    display_name: 김형식
    avatar: 'assets/images/team/김형식.jpg'
    email: hyungsik.kim@qraftec.com
    description: "CEO, Qraft Technologies"
  권혁환:
    name: 권혁환
    display_name: 권혁환
    avatar: 'assets/images/team/권혁환.jpg'
    email: hyukhwan.kwon@qraftec.com
    description: "Team Leader, AI Product Team"
  권택민:
    name: 권택민
    display_name: 권택민
    avatar: 'assets/images/team/avatar.png'
    email: taekmin.kwon@qraftec.com
    description: "AI Product Team"
  노승환:
    name: 노승환
    display_name: 노승환
    avatar: 'assets/images/team/roh.PNG'
    email: seunghwan.roh@qraftec.com
    description: "AI Product Team의 노승환입니다. 반갑습니다."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
